version: "2"

run:
  timeout: 2m

linters:
  default: standard
  enable:
    - testifylint
    - nolintlint
    - wsl_v5
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - gofumpt
    - goimports
