/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge/index'
import { Route as AuthenticatedKnowledgeNewRouteImport } from './routes/_authenticated/knowledge/new'
import { Route as AuthenticatedMcpTokensIndexRouteImport } from './routes/_authenticated/mcp-tokens/index'
import { Route as PublicKnowledgePublicIdRouteImport } from './routes/public/knowledge/$publicId'
import { Route as AuthenticatedKnowledgeKnowledgeIdEditRouteImport } from './routes/_authenticated/knowledge/$knowledgeId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/knowledge/index.lazy').then((d) => d.Route),
  )
const AuthenticatedKnowledgeNewRoute =
  AuthenticatedKnowledgeNewRouteImport.update({
    id: '/knowledge/new',
    path: '/knowledge/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/knowledge/new.lazy').then((d) => d.Route),
  )
const AuthenticatedMcpTokensIndexRoute =
  AuthenticatedMcpTokensIndexRouteImport.update({
    id: '/mcp-tokens/',
    path: '/mcp-tokens/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/mcp-tokens/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PublicKnowledgePublicIdRoute = PublicKnowledgePublicIdRouteImport.update({
  id: '/public/knowledge/$publicId',
  path: '/public/knowledge/$publicId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/public/knowledge/$publicId.lazy').then((d) => d.Route),
)
const AuthenticatedKnowledgeKnowledgeIdEditRoute =
  AuthenticatedKnowledgeKnowledgeIdEditRouteImport.update({
    id: '/knowledge/$knowledgeId/edit',
    path: '/knowledge/$knowledgeId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/knowledge/$knowledgeId/edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/public/knowledge/$publicId': typeof PublicKnowledgePublicIdRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/mcp-tokens/': typeof AuthenticatedMcpTokensIndexRoute
  '/knowledge/$knowledgeId/edit': typeof AuthenticatedKnowledgeKnowledgeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/public/knowledge/$publicId': typeof PublicKnowledgePublicIdRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/mcp-tokens': typeof AuthenticatedMcpTokensIndexRoute
  '/knowledge/$knowledgeId/edit': typeof AuthenticatedKnowledgeKnowledgeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/public/knowledge/$publicId': typeof PublicKnowledgePublicIdRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/mcp-tokens/': typeof AuthenticatedMcpTokensIndexRoute
  '/_authenticated/knowledge/$knowledgeId/edit': typeof AuthenticatedKnowledgeKnowledgeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/knowledge/new'
    | '/public/knowledge/$publicId'
    | '/knowledge/'
    | '/mcp-tokens/'
    | '/knowledge/$knowledgeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/knowledge/new'
    | '/public/knowledge/$publicId'
    | '/knowledge'
    | '/mcp-tokens'
    | '/knowledge/$knowledgeId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/knowledge/new'
    | '/public/knowledge/$publicId'
    | '/_authenticated/knowledge/'
    | '/_authenticated/mcp-tokens/'
    | '/_authenticated/knowledge/$knowledgeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicKnowledgePublicIdRoute: typeof PublicKnowledgePublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge/new': {
      id: '/_authenticated/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthenticatedKnowledgeNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mcp-tokens/': {
      id: '/_authenticated/mcp-tokens/'
      path: '/mcp-tokens'
      fullPath: '/mcp-tokens/'
      preLoaderRoute: typeof AuthenticatedMcpTokensIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public/knowledge/$publicId': {
      id: '/public/knowledge/$publicId'
      path: '/public/knowledge/$publicId'
      fullPath: '/public/knowledge/$publicId'
      preLoaderRoute: typeof PublicKnowledgePublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge/$knowledgeId/edit': {
      id: '/_authenticated/knowledge/$knowledgeId/edit'
      path: '/knowledge/$knowledgeId/edit'
      fullPath: '/knowledge/$knowledgeId/edit'
      preLoaderRoute: typeof AuthenticatedKnowledgeKnowledgeIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedKnowledgeNewRoute: typeof AuthenticatedKnowledgeNewRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedMcpTokensIndexRoute: typeof AuthenticatedMcpTokensIndexRoute
  AuthenticatedKnowledgeKnowledgeIdEditRoute: typeof AuthenticatedKnowledgeKnowledgeIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedKnowledgeNewRoute: AuthenticatedKnowledgeNewRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedMcpTokensIndexRoute: AuthenticatedMcpTokensIndexRoute,
  AuthenticatedKnowledgeKnowledgeIdEditRoute:
    AuthenticatedKnowledgeKnowledgeIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicKnowledgePublicIdRoute: PublicKnowledgePublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
